{"name": "test_login_failure_with_invalid_email", "status": "passed", "start": 1646855771979, "stop": 1646855783304, "uuid": "4bbf034f-17e4-4416-af99-97339ebabda5", "historyId": "cfa68c53724300caee3e8e2286a334b8", "testCaseId": "12e275a1d5ca77d9a4d9278e0cb683b1", "fullName": "tests.test_login.TestLogin#test_login_failure_with_invalid_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "W313879215ZMK"}, {"name": "thread", "value": "13360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}